# Generated by Django 3.2.23 on 2023-12-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkeyword',
            old_name='user',
            new_name='user_id',
        ),
    ]
