# Generated by Django 3.2.23 on 2023-12-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userkeywordtype',
            unique_together={('user_id', 'type')},
        ),
    ]
