server {
    listen 8080;
    server_name 49.50.166.153;
    charset utf-8;
    client_max_body_size 128M;

    location / {
        uwsgi_pass  unix:///tmp/mysite_.sock;
        include     uwsgi_params;
    }
        location /static/ {
                alias [/root/recrutam/client]
        }
}
