# Generated by Django 3.2.23 on 2023-12-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCareerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_id', models.IntegerField()),
                ('job_name', models.CharField(max_length=255)),
                ('job_description', models.CharField(max_length=255)),
                ('related_major', models.CharField(max_length=255)),
                ('certifications', models.CharField(max_length=255)),
                ('recommendation_reason', models.CharField(max_length=255)),
            ],
        ),
    ]
