# Generated by Django 3.2.23 on 2023-12-28 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCareerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('job_name', models.CharField(max_length=255)),
                ('job_description', models.CharField(max_length=255)),
                ('related_major', models.CharField(max_length=255)),
                ('certifications', models.CharField(max_length=255)),
                ('recommendation_reason', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
