# Generated by Django 3.2.23 on 2023-12-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercareeranalysis',
            old_name='user_id_id',
            new_name='user_id',
        ),
    ]
