# Generated by Django 3.2.23 on 2023-12-16 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('jobs', '0002_rename_user_id_id_usercareeranalysis_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercareeranalysis',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
